
package nl.marisabel.utils.location;

import javax.annotation.Generated;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

// PARENT CLASS

@JsonIgnoreProperties(ignoreUnknown = true)
@Generated("jsonschema2pojo")
public class Location {

	// create Object from the keys

	@SerializedName("city")
	@Expose
	private City city;

	@SerializedName("country")
	@Expose
	private Country country;

// generate getters and setters

	public City getCity() {
		return city;
	}

	public void setCity(City city) {
		this.city = city;
	}


	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	// String builder code autogenerated

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(Location.class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this)))
				.append('[');

		sb.append("city");
		sb.append('=');
		sb.append(((this.city == null) ? "<null>" : this.city));
		sb.append(',');
		sb.append("country");
		sb.append('=');
		sb.append(((this.country == null) ? "<null>" : this.country));
		sb.append(',');

		if (sb.charAt((sb.length() - 1)) == ',') {
			sb.setCharAt((sb.length() - 1), ']');
		} else {
			sb.append(']');
		}
		return sb.toString();
	}

}
